- hosts: all
#  connection: local
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - shell: ps -ef | grep itself | head -n5 > /home/ec2-user/test.ps
      register: ps

    # Print the shell task's stdout.
    - debug: msg={{ ps.stdout }}

    # Print all contents of the shell task's output.
    - debug: var=ps.rc
    - debug: var={{ var1 }}
